### ISSUE TITLE
ShootOFF's icon sucks.

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF-legacy#10]
We agree. All of the ShootOFF contributors at this point are scientists and engineers that would rather be doing math or coding. If you can do better, we'd appreciate it. A contribution should come in the form of a vector graphic with PNG outputs in at least 32x32, 48x48, 128x128, and 256x256. If there are other sizes you'd like to include for other window managers, we'll take 'em! Feel free to license your icon under any open source compatible license you like, we'll include the license with ShootOFF.

Same for YouTube videos!

**Comment by phrack** [comment]
We've been contacted by an individual with graphics artistry talents that has sent some concepts for a new ShootOFF icon. Seems sure enough to add this to the 1.4 milestone, but I'll remove it if the contributor needs to back out for some reason.

**Comment by farmerwd** [comment]
Hey all!

So I'm a designer laughably playing about in Git Hub and came across your nifty little program here. I'm a L.A.S.R. user but love the concept here... If you are ever in desperate need of any images or something let me know. I'm a designer by trade so I can donate some help to the cause. Not sure if I am too late or whatever, but I can definitely give it a shot (HA gun joke)

In any case I'm over at www.dannyfarmer.me, feel free to give me a shout.
-Danny

**Comment by phrack** [comment]
Awesome, thanks for the heads up! Probably won't need any images for a bit but I'll certainly keep you in mind.

**Comment by phrack** [comment]
Danny,

I just shot you a message through your site. Hoping we can discuss some ideas via email.
