### ISSUE TITLE
No way to adjust projection area for overscan on projector

### ISSUE THREAD

**Issue by setuidloot** [phrack/ShootOFF-legacy#119]
Overscan is used to refer to several things so I will clarify my usage. Overscan is where the projected area is smaller than the resolution of the source.  The projection area loses some small percentage of the edge of the source.  Effectively, the pixels all the way around the edge of the display area are lost.

For shootoff, the result is that the edges of the calibration squares in full screen mode are cut off.

In general, the area should be resizable so that overscan can be accounted for (If it is supposed to be resizable: it is not on Windows).

**Comment by phrack** [comment]
I don't think there is a way to detect overscan. Probably best to mitigate this by just adding a several pixel border to the canvas instead of having it be exactly the same size as the screen.
