### ISSUE TITLE
Windows full screen (F11) causes projection area to maximize on primary display, not current display

### ISSUE THREAD

**Issue by setuidloot** [phrack/ShootOFF-legacy#120]
I believe this is a "feature" of Windows, but I will leave it here for documentation purposes.

The only way I can full screen the projection area on the secondary display (projector) is to make my projector the primary display.

**Comment by phrack** [comment]
This is a won't fix because it's a bug in tkinter and tkinter makes it essentially impossible to work with the screen coordinate system reliably enough to figure out what the right dimensions should be to just fill the current screen.
