### ISSUE TITLE
Stability issues - Freezing

### ISSUE THREAD

**Issue by setuidloot** [phrack/ShootOFF-legacy#125]
Adding ISSF target to projector area caused freeze.  Could not reproduce.  No exceptions thrown

![freeze](https://cloud.githubusercontent.com/assets/5543934/6772364/b7d86490-d0d2-11e4-961e-14eee51ec5c6.png)

**Comment by phrack** [comment]
Seems like this and the crash are more likely to be problems in python itself. Why are you running the 32-bit version on 64-bit Windows?

PS. Definitely wasn't a problem on Ubuntu because I did both of the actions you did many times with no problems. Not duping on Arch either.
