### ISSUE TITLE
Stability issues - Crash

### ISSUE THREAD

**Issue by setuidloot** [phrack/ShootOFF-legacy#126]
Duel target training causes crash.  Was able to reproduce after adding dueling target and clicking on dueling training.  Also have had it happen when on dueling training and selecting "None" in training.  No python exceptions

Maybe audio related? I'm not getting any audio in anything either.  Might be duplicate issue with freezing #125 

![crash](https://cloud.githubusercontent.com/assets/5543934/6772388/152950b4-d0d3-11e4-99ec-d628ac3a7ad3.png)

**Comment by phrack** [comment]
As in #125, I suspect it's a problem with Python. Maybe see if there is a newer version or try 64-bit? These actions aren't causing these issues on Ubuntu or Arch.

**Comment by phrack** [comment]
On Arch: 

$ python2 --version
Python 2.7.9

**Comment by setuidloot** [comment]
it is 2.7.9.  to try 64bit i have to reinstall all the python packages.

**Comment by phrack** [comment]
I know that feel. Is the crash new to 2.1 after some of the recent commits, or is this the first time you've tried these features on this system? Trying to establish if this is because of something new in ShootOFF or if it's something unhelpable in the environment.

**Comment by setuidloot** [comment]
It is a new environment for testing.  Previously I had been testing on a Win7-64 environment.  This is a Win8.1-64.  I did notice that audio is not working.  My guess is that one of the packages, maybe pyttsx, is either not installed properly or does not like something about how it is being initialized.

I'm going to switch all the packages to 64bit and try it again.

Edit: and I can't test it on the win7 environment again, it no longer exists.

**Comment by setuidloot** [comment]
Audio works and it's not crashing with all 64bit libraries

I haven't tested everything but you can close these two issues and I'll open a new one for anything new.
