### ISSUE TITLE
Reset during Shoot-Don't Shoot causes exception

### ISSUE THREAD

**Issue by setuidloot** [phrack/ShootOFF-legacy#128]
![error on reset during shootdontshoot](https://cloud.githubusercontent.com/assets/5543934/6838772/508ea1fe-d335-11e4-8352-6b2a5ae9aca9.png)

My screenshot is a little messed up but the exception is shown

**Comment by phrack** [comment]
I just want to point out the hilarity that you're getting an item not found error on line 404.

**Comment by phrack** [comment]
115cdba9746fe75ca2e0fe8a3a4d10c95b4e2918
