### ISSUE TITLE
No score with ISSF protocol?

### ISSUE THREAD

**Issue by setuidloot** [phrack/ShootOFF-legacy#140]
![screenshot from 2015-04-09 01 28 16](https://cloud.githubusercontent.com/assets/5543934/7058926/ee364e7a-de57-11e4-903b-64e48abc3d8c.png)

Don't seem to get any score for hits, maybe i'm doing it wrong.

**Comment by phrack** [comment]
It should show the score on every hit. My guess is that it's not interacting with the arena correctly but would work if the target were instead added to the camera feed.

**Comment by phrack** [comment]
God dammit, I can't reproduce this one either. These last few bugs are _really_ annoying :(. 

![screenshot from 2015-04-09 17 11 46](https://cloud.githubusercontent.com/assets/174818/7077055/01741cc2-dedc-11e4-96c2-ed23be4d4195.png)

**Comment by setuidloot** [comment]
Not able to reproduce but I've got a different ISSF protocol bug.  Can shoot in a round more than 5 times.

Seems to ignore hits, counts misses.

![screenshot from 2015-04-12 03 57 18](https://cloud.githubusercontent.com/assets/5543934/7104341/466d5a44-e0c8-11e4-8e53-71aae51035d1.png)

**Comment by setuidloot** [comment]
My thought on the original bug is that I broke something with the don't shoot/shoot protocol that caused the zero scores in ISSF.

**Comment by phrack** [comment]
This is a race condition, but one that I don't consider to be worth fixing in a retiring code base given that it isn't counting hits. I am going to call this issue closed.
