### ISSUE TITLE
Training protocol creators should be able to simulate shots by clicking the webcam feed to make it easier to test their protocols.

### ISSUE THREAD

**Issue by phrack** [phrack/ShootOFF-legacy#44]
This should probably be a feature that is only on in debug mode. Holding one hotkey and clicking should simulate red shots and holding another hotkey and clicking should simulate green shots.

This idea was envisioned and incorporated by MisterOuchie in https://github.com/phrack/ShootOFF/pull/46.

**Comment by MisterOuchie** [comment]
I had a go at changing my prior implementation of this to what is described above.

**Comment by phrack** [comment]
Very cool, thanks for changing course on this! I thought your idea was wonderful and just needed a few more steps forward to be dead on the money. I am planning to get to your pull request within the next week as long as Thanksgiving doesn't slow me down too much.
