### ISSUE TITLE
Recommend changing shot highlighting behavior

### ISSUE THREAD

**Issue by setuidloot** [phrack/ShootOFF-legacy#55]
Right now, the shot is outlined in yellow when it is selected in the shot list.  yellow around green, even when the marker is large, is hard to see.

Possible solutions: 

Dynamically choose contrasting color
Highlight entire shot instead of outline (The color is shown in the shot list anyway)
Some kind of pointer or indicator instead of just color change
User customized behavior

**Comment by phrack** [comment]
One of these is going to be the easiest solution:
1. Color the selected shot solid gold instead of just outlining it.
2. Make the selected shot slightly bigger only while it is selected.
