### ISSUE TITLE
Problem with webcam Logitech Inc. QuickCam Communicate MP/S5500

### ISSUE THREAD

**Issue by aleandrodasilva** [phrack/ShootOFF-legacy#62]
Hello,

I tried to run the program with this webcam model Logitech, Inc. QuickCam Communicate MP/S5500.
http://www.logitech.com/en-us/support/4224?crid=405

I get following error:

VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
HIGHGUI ERROR: V4L2: Unable to get property <unknown property string>(5) - Invalid argument
2014-08-30 11:57:45,862 - shootoff - INFO - Couldn't get webcam FPS, defaulting to 30.
2014-08-30 11:57:46,285 - shootoff - WARNING - Glare or light source detected. 0.000000 of the image is dark.

Any idea how to set the proper fps and letting the program to detect it properly?

**Comment by phrack** [comment]
The exact FPS value doesn't actually matter as long as the frame is being refreshed fast enough to detect your shots. Some information, such as the FPS for the camera, can be looked up automatically for some cameras. In your case, you have a camera where this information is not available from the camera driver. ShootOFF attempts to use a sane value in the event that it cannot look up the actual value, and it is usually either correct or good enough.

**Comment by phrack** [comment]
I am closing this issue because I believe my comment addressed it. You can still comment if I am wrong.
